
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int program = 2;
  public static final int or_op = 43;
  public static final int function = 16;
  public static final int if_t = 7;
  public static final int plus = 37;
  public static final int colons = 23;
  public static final int array = 45;
  public static final int minus = 38;
  public static final int asig = 24;
  public static final int for_t = 11;
  public static final int comma = 26;
  public static final int identifier = 47;
  public static final int begin = 3;
  public static final int end = 4;
  public static final int equal = 25;
  public static final int comparator_op = 32;
  public static final int two_points = 44;
  public static final int var = 5;
  public static final int EOF = 0;
  public static final int mod_op = 41;
  public static final int error = 1;
  public static final int open_bracket = 28;
  public static final int and_op = 42;
  public static final int procedure = 17;
  public static final int not_op = 33;
  public static final int decimal_value = 34;
  public static final int point = 27;
  public static final int while_t = 10;
  public static final int int_name = 19;
  public static final int char_name = 21;
  public static final int product = 39;
  public static final int of = 15;
  public static final int record = 46;
  public static final int real_name = 20;
  public static final int open_square_bracket = 30;
  public static final int semicolons = 22;
  public static final int string_literal = 36;
  public static final int hexadecimal_value = 35;
  public static final int case_t = 14;
  public static final int else_t = 9;
  public static final int then_t = 8;
  public static final int div_op = 40;
  public static final int close_square_bracket = 31;
  public static final int do_t = 13;
  public static final int to = 12;
  public static final int const_t = 6;
  public static final int close_bracket = 29;
  public static final int type = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "program",
  "begin",
  "end",
  "var",
  "const_t",
  "if_t",
  "then_t",
  "else_t",
  "while_t",
  "for_t",
  "to",
  "do_t",
  "case_t",
  "of",
  "function",
  "procedure",
  "type",
  "int_name",
  "real_name",
  "char_name",
  "semicolons",
  "colons",
  "asig",
  "equal",
  "comma",
  "point",
  "open_bracket",
  "close_bracket",
  "open_square_bracket",
  "close_square_bracket",
  "comparator_op",
  "not_op",
  "decimal_value",
  "hexadecimal_value",
  "string_literal",
  "plus",
  "minus",
  "product",
  "div_op",
  "mod_op",
  "and_op",
  "or_op",
  "two_points",
  "array",
  "record",
  "identifier"
  };
}

