/* The following code was generated by JFlex 1.6.1 */

// {Codigo de usuario}

// IMPORTS
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>Gramatica.flex</tt>
 */
class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\23\1\13\1\15\1\16\1\14\22\0\1\23\1\0\1\74"+
    "\1\0\1\5\2\0\1\72\1\20\1\22\1\21\1\71\1\65\1\4"+
    "\1\66\1\0\12\2\1\64\1\63\1\7\1\10\1\6\2\0\1\57"+
    "\1\3\1\61\1\3\1\54\1\3\1\55\1\62\1\51\2\1\1\60"+
    "\1\1\1\52\3\1\1\56\1\1\1\53\6\1\1\67\1\73\1\70"+
    "\1\0\1\1\1\0\1\30\1\32\1\40\1\36\1\33\1\43\1\27"+
    "\1\44\1\34\2\1\1\45\1\31\1\35\1\26\1\24\1\1\1\25"+
    "\1\41\1\42\1\47\1\37\1\46\1\1\1\50\1\1\1\12\1\0"+
    "\1\17\7\0\1\15\44\0\1\11\12\0\1\11\4\0\1\11\5\0"+
    "\27\11\1\0\37\11\1\0\u01ca\11\4\0\14\11\16\0\5\11\7\0"+
    "\1\11\1\0\1\11\21\0\165\11\1\0\2\11\2\0\4\11\1\0"+
    "\1\11\6\0\1\11\1\0\3\11\1\0\1\11\1\0\24\11\1\0"+
    "\123\11\1\0\213\11\1\0\255\11\1\0\46\11\2\0\1\11\7\0"+
    "\47\11\11\0\55\11\1\0\1\11\1\0\2\11\1\0\2\11\1\0"+
    "\1\11\10\0\33\11\5\0\3\11\35\0\13\11\5\0\112\11\4\0"+
    "\146\11\1\0\10\11\2\0\12\11\1\0\23\11\2\0\1\11\20\0"+
    "\73\11\2\0\145\11\16\0\66\11\4\0\1\11\5\0\56\11\22\0"+
    "\34\11\104\0\23\11\61\0\200\11\2\0\12\11\1\0\23\11\1\0"+
    "\10\11\2\0\2\11\2\0\26\11\1\0\7\11\1\0\1\11\3\0"+
    "\4\11\2\0\11\11\2\0\2\11\2\0\4\11\10\0\1\11\4\0"+
    "\2\11\1\0\5\11\2\0\14\11\17\0\3\11\1\0\6\11\4\0"+
    "\2\11\2\0\26\11\1\0\7\11\1\0\2\11\1\0\2\11\1\0"+
    "\2\11\2\0\1\11\1\0\5\11\4\0\2\11\2\0\3\11\3\0"+
    "\1\11\7\0\4\11\1\0\1\11\7\0\20\11\13\0\3\11\1\0"+
    "\11\11\1\0\3\11\1\0\26\11\1\0\7\11\1\0\2\11\1\0"+
    "\5\11\2\0\12\11\1\0\3\11\1\0\3\11\2\0\1\11\17\0"+
    "\4\11\2\0\12\11\21\0\3\11\1\0\10\11\2\0\2\11\2\0"+
    "\26\11\1\0\7\11\1\0\2\11\1\0\5\11\2\0\11\11\2\0"+
    "\2\11\2\0\3\11\10\0\2\11\4\0\2\11\1\0\5\11\2\0"+
    "\12\11\1\0\1\11\20\0\2\11\1\0\6\11\3\0\3\11\1\0"+
    "\4\11\3\0\2\11\1\0\1\11\1\0\2\11\3\0\2\11\3\0"+
    "\3\11\3\0\14\11\4\0\5\11\3\0\3\11\1\0\4\11\2\0"+
    "\1\11\6\0\1\11\16\0\12\11\20\0\4\11\1\0\10\11\1\0"+
    "\3\11\1\0\27\11\1\0\20\11\3\0\10\11\1\0\3\11\1\0"+
    "\4\11\7\0\2\11\1\0\2\11\6\0\4\11\2\0\12\11\21\0"+
    "\3\11\1\0\10\11\1\0\3\11\1\0\27\11\1\0\12\11\1\0"+
    "\5\11\2\0\11\11\1\0\3\11\1\0\4\11\7\0\2\11\7\0"+
    "\1\11\1\0\4\11\2\0\12\11\1\0\2\11\16\0\3\11\1\0"+
    "\10\11\1\0\3\11\1\0\51\11\2\0\10\11\1\0\3\11\1\0"+
    "\5\11\10\0\1\11\10\0\4\11\2\0\12\11\12\0\6\11\2\0"+
    "\2\11\1\0\22\11\3\0\30\11\1\0\11\11\1\0\1\11\2\0"+
    "\7\11\3\0\1\11\4\0\6\11\1\0\1\11\1\0\10\11\6\0"+
    "\12\11\2\0\2\11\15\0\72\11\5\0\17\11\1\0\12\11\47\0"+
    "\2\11\1\0\1\11\2\0\2\11\1\0\1\11\2\0\1\11\6\0"+
    "\4\11\1\0\7\11\1\0\3\11\1\0\1\11\1\0\1\11\2\0"+
    "\2\11\1\0\15\11\1\0\3\11\2\0\5\11\1\0\1\11\1\0"+
    "\6\11\2\0\12\11\2\0\4\11\40\0\1\11\27\0\2\11\6\0"+
    "\12\11\13\0\1\11\1\0\1\11\1\0\1\11\4\0\12\11\1\0"+
    "\44\11\4\0\24\11\1\0\22\11\1\0\44\11\11\0\1\11\71\0"+
    "\112\11\6\0\116\11\2\0\46\11\1\0\1\11\5\0\1\11\2\0"+
    "\53\11\1\0\u014d\11\1\0\4\11\2\0\7\11\1\0\1\11\1\0"+
    "\4\11\2\0\51\11\1\0\4\11\2\0\41\11\1\0\4\11\2\0"+
    "\7\11\1\0\1\11\1\0\4\11\2\0\17\11\1\0\71\11\1\0"+
    "\4\11\2\0\103\11\2\0\3\11\40\0\20\11\20\0\125\11\14\0"+
    "\u026c\11\2\0\21\11\1\0\32\11\5\0\113\11\3\0\13\11\7\0"+
    "\15\11\1\0\7\11\13\0\25\11\13\0\24\11\14\0\15\11\1\0"+
    "\3\11\1\0\2\11\14\0\124\11\3\0\1\11\4\0\2\11\2\0"+
    "\12\11\41\0\3\11\2\0\12\11\6\0\130\11\10\0\53\11\5\0"+
    "\106\11\12\0\37\11\1\0\14\11\4\0\14\11\12\0\50\11\2\0"+
    "\5\11\13\0\54\11\4\0\32\11\6\0\12\11\46\0\34\11\4\0"+
    "\77\11\1\0\35\11\2\0\13\11\6\0\12\11\15\0\1\11\10\0"+
    "\17\11\101\0\114\11\4\0\12\11\21\0\11\11\14\0\164\11\14\0"+
    "\70\11\10\0\12\11\3\0\61\11\122\0\3\11\1\0\43\11\1\0"+
    "\2\11\6\0\366\11\6\0\u011a\11\2\0\6\11\2\0\46\11\2\0"+
    "\6\11\2\0\10\11\1\0\1\11\1\0\1\11\1\0\1\11\1\0"+
    "\37\11\2\0\65\11\1\0\7\11\1\0\1\11\3\0\3\11\1\0"+
    "\7\11\3\0\4\11\2\0\6\11\4\0\15\11\5\0\3\11\1\0"+
    "\7\11\53\0\1\15\1\15\25\0\2\11\23\0\1\11\34\0\1\11"+
    "\15\0\1\11\20\0\15\11\63\0\41\11\21\0\1\11\4\0\1\11"+
    "\2\0\12\11\1\0\1\11\3\0\5\11\6\0\1\11\1\0\1\11"+
    "\1\0\1\11\1\0\4\11\1\0\13\11\2\0\4\11\5\0\5\11"+
    "\4\0\1\11\21\0\51\11\u032d\0\64\11\u0716\0\57\11\1\0\57\11"+
    "\1\0\205\11\6\0\11\11\14\0\46\11\1\0\1\11\5\0\1\11"+
    "\2\0\70\11\7\0\1\11\17\0\30\11\11\0\7\11\1\0\7\11"+
    "\1\0\7\11\1\0\7\11\1\0\7\11\1\0\7\11\1\0\7\11"+
    "\1\0\7\11\1\0\40\11\57\0\1\11\u01d5\0\3\11\31\0\17\11"+
    "\1\0\5\11\2\0\5\11\4\0\126\11\2\0\2\11\2\0\3\11"+
    "\1\0\132\11\1\0\4\11\5\0\51\11\3\0\136\11\21\0\33\11"+
    "\65\0\20\11\u0200\0\u19b6\11\112\0\u51cd\11\63\0\u048d\11\103\0\56\11"+
    "\2\0\u010d\11\3\0\34\11\24\0\63\11\1\0\12\11\1\0\37\11"+
    "\1\0\123\11\45\0\11\11\2\0\147\11\2\0\4\11\1\0\36\11"+
    "\2\0\2\11\105\0\61\11\30\0\64\11\14\0\105\11\13\0\12\11"+
    "\6\0\30\11\3\0\1\11\4\0\56\11\2\0\44\11\14\0\35\11"+
    "\3\0\101\11\16\0\13\11\6\0\37\11\1\0\67\11\11\0\16\11"+
    "\2\0\12\11\6\0\27\11\3\0\111\11\30\0\3\11\2\0\20\11"+
    "\2\0\5\11\12\0\6\11\2\0\6\11\2\0\6\11\11\0\7\11"+
    "\1\0\7\11\1\0\53\11\1\0\4\11\4\0\2\11\132\0\53\11"+
    "\1\0\2\11\2\0\12\11\6\0\u2ba4\11\14\0\27\11\4\0\61\11"+
    "\u2104\0\u016e\11\2\0\152\11\46\0\7\11\14\0\5\11\5\0\14\11"+
    "\1\0\15\11\1\0\5\11\1\0\1\11\1\0\2\11\1\0\2\11"+
    "\1\0\154\11\41\0\u016b\11\22\0\100\11\2\0\66\11\50\0\14\11"+
    "\4\0\20\11\20\0\16\11\5\0\2\11\30\0\3\11\40\0\5\11"+
    "\1\0\207\11\23\0\12\11\7\0\32\11\4\0\1\11\1\0\32\11"+
    "\13\0\131\11\3\0\6\11\2\0\6\11\2\0\6\11\2\0\3\11"+
    "\43\0\14\11\1\0\32\11\1\0\23\11\1\0\2\11\1\0\17\11"+
    "\2\0\16\11\42\0\173\11\105\0\65\11\210\0\1\11\202\0\35\11"+
    "\3\0\61\11\17\0\1\11\37\0\40\11\20\0\33\11\5\0\53\11"+
    "\5\0\36\11\2\0\44\11\4\0\10\11\1\0\5\11\52\0\236\11"+
    "\2\0\12\11\126\0\50\11\10\0\64\11\234\0\u0137\11\11\0\26\11"+
    "\12\0\10\11\230\0\6\11\2\0\1\11\1\0\54\11\1\0\2\11"+
    "\3\0\1\11\2\0\27\11\12\0\27\11\11\0\37\11\141\0\26\11"+
    "\12\0\32\11\106\0\70\11\6\0\2\11\100\0\4\11\1\0\2\11"+
    "\5\0\10\11\1\0\3\11\1\0\33\11\4\0\3\11\4\0\1\11"+
    "\40\0\35\11\3\0\35\11\43\0\10\11\1\0\36\11\31\0\66\11"+
    "\12\0\26\11\12\0\23\11\15\0\22\11\156\0\111\11\u03b7\0\107\11"+
    "\37\0\12\11\17\0\74\11\25\0\31\11\7\0\12\11\6\0\65\11"+
    "\1\0\12\11\20\0\44\11\2\0\1\11\11\0\105\11\13\0\13\11"+
    "\45\0\22\11\1\0\45\11\170\0\73\11\5\0\12\11\7\0\3\11"+
    "\1\0\10\11\2\0\2\11\2\0\26\11\1\0\7\11\1\0\2\11"+
    "\1\0\5\11\2\0\11\11\2\0\2\11\2\0\3\11\11\0\1\11"+
    "\5\0\7\11\2\0\7\11\3\0\5\11\u010b\0\106\11\1\0\1\11"+
    "\10\0\12\11\246\0\66\11\2\0\11\11\77\0\101\11\3\0\1\11"+
    "\13\0\12\11\46\0\70\11\10\0\12\11\u01d6\0\112\11\25\0\1\11"+
    "\u01c0\0\71\11\u0507\0\u0399\11\147\0\157\11\u0b91\0\u042f\11\u33d1\0\u0239\11"+
    "\7\0\37\11\1\0\12\11\146\0\36\11\2\0\5\11\13\0\67\11"+
    "\11\0\4\11\14\0\12\11\11\0\25\11\5\0\23\11\u0370\0\105\11"+
    "\13\0\57\11\20\0\21\11\u4060\0\2\11\u0bfe\0\153\11\5\0\15\11"+
    "\3\0\11\11\7\0\12\11\3\0\2\11\u14c6\0\5\11\3\0\6\11"+
    "\10\0\10\11\2\0\7\11\36\0\4\11\224\0\3\11\u01bb\0\125\11"+
    "\1\0\107\11\1\0\2\11\2\0\1\11\2\0\2\11\2\0\4\11"+
    "\1\0\14\11\1\0\1\11\1\0\7\11\1\0\101\11\1\0\4\11"+
    "\2\0\10\11\1\0\7\11\1\0\34\11\1\0\4\11\1\0\5\11"+
    "\1\0\1\11\3\0\7\11\1\0\u0154\11\2\0\31\11\1\0\31\11"+
    "\1\0\37\11\1\0\31\11\1\0\37\11\1\0\31\11\1\0\37\11"+
    "\1\0\31\11\1\0\37\11\1\0\31\11\1\0\10\11\2\0\62\11"+
    "\u1000\0\305\11\13\0\7\11\u0529\0\4\11\1\0\33\11\1\0\2\11"+
    "\1\0\1\11\2\0\1\11\1\0\12\11\1\0\4\11\1\0\1\11"+
    "\1\0\1\11\6\0\1\11\4\0\1\11\1\0\1\11\1\0\1\11"+
    "\1\0\3\11\1\0\2\11\1\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\1\0\1\11\1\0\1\11\1\0\2\11\1\0\1\11"+
    "\2\0\4\11\1\0\7\11\1\0\4\11\1\0\4\11\1\0\1\11"+
    "\1\0\12\11\1\0\21\11\5\0\3\11\1\0\5\11\1\0\21\11"+
    "\u0274\0\32\11\6\0\32\11\6\0\32\11\u0e76\0\ua6d7\11\51\0\u1035\11"+
    "\13\0\336\11\u3fe2\0\u021e\11\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u06ed\0"+
    "\360\11\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\1\2\5\1\6"+
    "\1\1\2\7\1\10\1\11\1\12\22\2\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\0\1\26\1\0\1\5\1\0\1\7\1\0"+
    "\2\2\1\27\1\30\6\2\1\31\1\2\1\32\4\2"+
    "\1\33\10\2\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\3\2\0\3\2\1\43\1\44\1\2\1\45"+
    "\1\2\1\46\1\47\1\50\4\2\1\51\5\2\1\26"+
    "\1\7\5\2\1\52\1\2\1\53\1\54\1\55\3\2"+
    "\1\56\4\2\1\57\1\60\1\61\1\2\1\62\4\2"+
    "\1\63\3\2\1\64\2\2\1\65\2\2\1\66\1\2"+
    "\1\67\1\70";

  private static int [] zzUnpackAction() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\267\0\364\0\u0131\0\u016e\0\u01ab"+
    "\0\u01e8\0\172\0\u0225\0\172\0\u0262\0\u029f\0\172\0\172"+
    "\0\u02dc\0\u0319\0\u0356\0\u0393\0\u03d0\0\u040d\0\u044a\0\u0487"+
    "\0\u04c4\0\u0501\0\u053e\0\u057b\0\u05b8\0\u05f5\0\u0632\0\u066f"+
    "\0\u06ac\0\u06e9\0\172\0\u0726\0\172\0\u0763\0\172\0\172"+
    "\0\u0131\0\172\0\u07a0\0\u07dd\0\u081a\0\u0857\0\u0894\0\u08d1"+
    "\0\172\0\u0225\0\u0225\0\u090e\0\u094b\0\u0988\0\267\0\267"+
    "\0\u09c5\0\u0a02\0\u0a3f\0\u0a7c\0\u0ab9\0\u0af6\0\267\0\u0b33"+
    "\0\267\0\u0b70\0\u0bad\0\u0bea\0\u0c27\0\267\0\u0c64\0\u0ca1"+
    "\0\u0cde\0\u0d1b\0\u0d58\0\u0d95\0\u0dd2\0\u0e0f\0\172\0\172"+
    "\0\172\0\172\0\172\0\172\0\172\0\u0857\0\u0e4c\0\u0e89"+
    "\0\u0ec6\0\u0f03\0\u0f40\0\267\0\267\0\u0f7d\0\267\0\u0fba"+
    "\0\267\0\267\0\267\0\u0ff7\0\u1034\0\u1071\0\u10ae\0\267"+
    "\0\u10eb\0\u1128\0\u1165\0\u11a2\0\u11df\0\u0e4c\0\u090e\0\u121c"+
    "\0\u1259\0\u1296\0\u12d3\0\u1310\0\267\0\u134d\0\267\0\267"+
    "\0\267\0\u138a\0\u13c7\0\u1404\0\267\0\u1441\0\u147e\0\u14bb"+
    "\0\u14f8\0\267\0\267\0\267\0\u1535\0\267\0\u1572\0\u15af"+
    "\0\u15ec\0\u1629\0\267\0\u1666\0\u16a3\0\u16e0\0\267\0\u171d"+
    "\0\u175a\0\267\0\u1797\0\u17d4\0\267\0\u1811\0\267\0\267";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\4\1\6\1\7\1\10\1\11"+
    "\1\12\1\3\1\13\1\14\1\15\1\3\1\14\1\3"+
    "\1\16\1\17\1\20\1\14\1\21\1\22\1\23\1\4"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\4\1\35\1\36\2\4\1\37\2\4\1\40"+
    "\4\4\1\41\2\4\1\42\1\4\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\2\3\13\53\2\0"+
    "\55\53\1\54\1\55\1\53\76\0\3\4\5\0\1\4"+
    "\12\0\37\4\14\0\1\5\63\0\1\56\10\0\1\5"+
    "\74\0\2\57\1\60\47\0\1\57\2\0\1\57\1\0"+
    "\1\57\7\0\1\60\13\0\1\61\72\0\1\61\1\0"+
    "\1\61\64\0\13\62\4\0\1\63\55\62\13\0\1\14"+
    "\102\0\1\64\54\0\3\4\5\0\1\4\12\0\1\4"+
    "\1\65\35\4\13\0\3\4\5\0\1\4\12\0\7\4"+
    "\1\66\27\4\13\0\3\4\5\0\1\4\12\0\1\4"+
    "\1\67\15\4\1\70\17\4\13\0\3\4\5\0\1\4"+
    "\12\0\1\4\1\71\7\4\1\72\25\4\13\0\3\4"+
    "\5\0\1\4\12\0\2\4\1\73\34\4\13\0\3\4"+
    "\5\0\1\4\12\0\7\4\1\74\27\4\13\0\3\4"+
    "\5\0\1\4\12\0\11\4\1\75\7\4\1\76\15\4"+
    "\13\0\3\4\5\0\1\4\12\0\17\4\1\77\17\4"+
    "\13\0\3\4\5\0\1\4\12\0\2\4\1\100\34\4"+
    "\13\0\3\4\5\0\1\4\12\0\2\4\1\101\5\4"+
    "\1\102\26\4\13\0\3\4\5\0\1\4\12\0\4\4"+
    "\1\103\32\4\13\0\3\4\5\0\1\4\12\0\2\4"+
    "\1\104\1\4\1\105\32\4\13\0\3\4\5\0\1\4"+
    "\12\0\2\4\1\106\15\4\1\107\3\4\1\110\12\4"+
    "\13\0\3\4\5\0\1\4\12\0\2\4\1\111\20\4"+
    "\1\112\13\4\13\0\3\4\5\0\1\4\12\0\20\4"+
    "\1\113\16\4\13\0\3\4\5\0\1\4\12\0\26\4"+
    "\1\114\10\4\13\0\3\4\5\0\1\4\12\0\30\4"+
    "\1\115\6\4\13\0\3\4\5\0\1\4\12\0\36\4"+
    "\1\116\22\0\1\117\152\0\1\120\6\0\13\53\2\0"+
    "\55\53\2\0\1\53\72\0\1\121\27\0\1\122\7\0"+
    "\1\123\4\0\1\124\31\0\1\125\2\0\1\126\74\0"+
    "\2\57\50\0\1\57\2\0\1\57\1\0\1\57\4\0"+
    "\1\127\10\0\2\57\50\0\1\57\2\0\1\57\1\0"+
    "\1\57\13\0\13\64\4\0\2\64\1\130\53\64\1\0"+
    "\3\4\5\0\1\4\12\0\2\4\1\131\34\4\13\0"+
    "\3\4\5\0\1\4\12\0\14\4\1\132\22\4\13\0"+
    "\3\4\5\0\1\4\12\0\1\4\1\133\35\4\13\0"+
    "\3\4\5\0\1\4\12\0\12\4\1\134\24\4\13\0"+
    "\3\4\5\0\1\4\12\0\12\4\1\135\24\4\13\0"+
    "\3\4\5\0\1\4\12\0\3\4\1\136\33\4\13\0"+
    "\3\4\5\0\1\4\12\0\12\4\1\137\24\4\13\0"+
    "\3\4\5\0\1\4\12\0\15\4\1\140\21\4\13\0"+
    "\3\4\5\0\1\4\12\0\16\4\1\141\20\4\13\0"+
    "\3\4\5\0\1\4\12\0\13\4\1\142\23\4\13\0"+
    "\3\4\5\0\1\4\12\0\1\4\1\143\35\4\13\0"+
    "\3\4\5\0\1\4\12\0\11\4\1\144\25\4\13\0"+
    "\3\4\5\0\1\4\12\0\15\4\1\145\21\4\13\0"+
    "\3\4\5\0\1\4\12\0\7\4\1\146\27\4\13\0"+
    "\3\4\5\0\1\4\12\0\1\147\36\4\13\0\3\4"+
    "\5\0\1\4\12\0\1\4\1\150\35\4\13\0\3\4"+
    "\5\0\1\4\12\0\11\4\1\151\25\4\13\0\3\4"+
    "\5\0\1\4\12\0\10\4\1\152\26\4\13\0\3\4"+
    "\5\0\1\4\12\0\27\4\1\153\7\4\13\0\3\4"+
    "\5\0\1\4\12\0\33\4\1\154\3\4\13\0\3\4"+
    "\5\0\1\4\12\0\33\4\1\155\3\4\14\0\2\156"+
    "\50\0\1\156\2\0\1\156\1\0\1\156\13\0\13\64"+
    "\4\0\2\64\1\130\1\157\52\64\1\0\3\4\5\0"+
    "\1\4\12\0\3\4\1\160\10\4\1\161\22\4\13\0"+
    "\3\4\5\0\1\4\12\0\2\4\1\162\34\4\13\0"+
    "\3\4\5\0\1\4\12\0\4\4\1\163\32\4\13\0"+
    "\3\4\5\0\1\4\12\0\10\4\1\164\26\4\13\0"+
    "\3\4\5\0\1\4\12\0\7\4\1\165\27\4\13\0"+
    "\3\4\5\0\1\4\12\0\15\4\1\166\21\4\13\0"+
    "\3\4\5\0\1\4\12\0\7\4\1\167\27\4\13\0"+
    "\3\4\5\0\1\4\12\0\11\4\1\170\25\4\13\0"+
    "\3\4\5\0\1\4\12\0\7\4\1\171\27\4\13\0"+
    "\3\4\5\0\1\4\12\0\14\4\1\172\22\4\13\0"+
    "\3\4\5\0\1\4\12\0\21\4\1\173\15\4\13\0"+
    "\3\4\5\0\1\4\12\0\30\4\1\174\6\4\13\0"+
    "\3\4\5\0\1\4\12\0\34\4\1\175\2\4\13\0"+
    "\3\4\5\0\1\4\12\0\32\4\1\176\4\4\13\0"+
    "\3\4\5\0\1\4\12\0\1\4\1\177\35\4\13\0"+
    "\3\4\5\0\1\4\12\0\7\4\1\200\27\4\13\0"+
    "\3\4\5\0\1\4\12\0\1\4\1\201\35\4\13\0"+
    "\3\4\5\0\1\4\12\0\24\4\1\202\12\4\13\0"+
    "\3\4\5\0\1\4\12\0\11\4\1\203\25\4\13\0"+
    "\3\4\5\0\1\4\12\0\16\4\1\204\20\4\13\0"+
    "\3\4\5\0\1\4\12\0\16\4\1\205\20\4\13\0"+
    "\3\4\5\0\1\4\12\0\7\4\1\206\27\4\13\0"+
    "\3\4\5\0\1\4\12\0\31\4\1\207\5\4\13\0"+
    "\3\4\5\0\1\4\12\0\33\4\1\210\3\4\13\0"+
    "\3\4\5\0\1\4\12\0\4\4\1\211\32\4\13\0"+
    "\3\4\5\0\1\4\12\0\12\4\1\212\24\4\13\0"+
    "\3\4\5\0\1\4\12\0\12\4\1\213\24\4\13\0"+
    "\3\4\5\0\1\4\12\0\10\4\1\214\26\4\13\0"+
    "\3\4\5\0\1\4\12\0\30\4\1\215\6\4\13\0"+
    "\3\4\5\0\1\4\12\0\35\4\1\216\1\4\13\0"+
    "\3\4\5\0\1\4\12\0\5\4\1\217\31\4\13\0"+
    "\3\4\5\0\1\4\12\0\23\4\1\220\13\4\13\0"+
    "\3\4\5\0\1\4\12\0\2\4\1\221\34\4\13\0"+
    "\3\4\5\0\1\4\12\0\32\4\1\222\4\4\13\0"+
    "\3\4\5\0\1\4\12\0\27\4\1\223\7\4\13\0"+
    "\3\4\5\0\1\4\12\0\1\4\1\224\35\4\13\0"+
    "\3\4\5\0\1\4\12\0\11\4\1\225\25\4\13\0"+
    "\3\4\5\0\1\4\12\0\30\4\1\226\6\4\13\0"+
    "\3\4\5\0\1\4\12\0\7\4\1\227\27\4\13\0"+
    "\3\4\5\0\1\4\12\0\32\4\1\230\4\4\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6222];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\6\1\1\11\1\1\1\11\2\1\2\11"+
    "\22\1\1\11\1\1\1\11\1\1\2\11\1\1\1\11"+
    "\3\1\1\0\1\1\1\0\1\11\1\0\1\1\1\0"+
    "\32\1\7\11\1\1\2\0\100\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	StringBuffer string = new StringBuffer();

	private Symbol symbol(int type) {
    return new java_cup.runtime.Symbol(type, yyline, yycolumn);
  }

  private Symbol symbol(int type, Object value) {
    return new java_cup.runtime.Symbol(type, yyline, yycolumn, value);
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2700) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Cadena no valida:  \""+yytext()+
		                                                              "\" en la linea "+(yyline+1)+", columna "+yycolumn);
            }
          case 57: break;
          case 2: 
            { return symbol(sym.identifier, yytext());
            }
          case 58: break;
          case 3: 
            { return symbol(sym.decimal_value, yytext());
            }
          case 59: break;
          case 4: 
            { return symbol(sym.minus);
            }
          case 60: break;
          case 5: 
            { return symbol(sym.comparator_op, yytext());
            }
          case 61: break;
          case 6: 
            { return symbol(sym.equal);
            }
          case 62: break;
          case 7: 
            { /* IGNORAR */
            }
          case 63: break;
          case 8: 
            { return symbol(sym.open_bracket);
            }
          case 64: break;
          case 9: 
            { return symbol(sym.product);
            }
          case 65: break;
          case 10: 
            { return symbol(sym.close_bracket);
            }
          case 66: break;
          case 11: 
            { return symbol(sym.semicolons);
            }
          case 67: break;
          case 12: 
            { return symbol(sym.colons);
            }
          case 68: break;
          case 13: 
            { return symbol(sym.comma);
            }
          case 69: break;
          case 14: 
            { return symbol(sym.point);
            }
          case 70: break;
          case 15: 
            { return symbol(sym.open_square_bracket);
            }
          case 71: break;
          case 16: 
            { return symbol(sym.close_square_bracket);
            }
          case 72: break;
          case 17: 
            { return symbol(sym.plus);
            }
          case 73: break;
          case 18: 
            { string.setLength(0);
      yybegin(STRING);
            }
          case 74: break;
          case 19: 
            { string.append( yytext() );
            }
          case 75: break;
          case 20: 
            { yybegin(YYINITIAL); return symbol(sym.string_literal, string.toString());
            }
          case 76: break;
          case 21: 
            { string.append('\\');
            }
          case 77: break;
          case 22: 
            { return symbol(sym.hexadecimal_value, yytext());
            }
          case 78: break;
          case 23: 
            { return symbol(sym.or_op);
            }
          case 79: break;
          case 24: 
            { return symbol(sym.of);
            }
          case 80: break;
          case 25: 
            { return symbol(sym.if_t);
            }
          case 81: break;
          case 26: 
            { return symbol(sym.do_t);
            }
          case 82: break;
          case 27: 
            { return symbol(sym.to);
            }
          case 83: break;
          case 28: 
            { return symbol(sym.asig);
            }
          case 84: break;
          case 29: 
            { return symbol(sym.two_points);
            }
          case 85: break;
          case 30: 
            { string.append('\'');
            }
          case 86: break;
          case 31: 
            { string.append('\r');
            }
          case 87: break;
          case 32: 
            { string.append('\n');
            }
          case 88: break;
          case 33: 
            { string.append('\t');
            }
          case 89: break;
          case 34: 
            { string.append('\"');
            }
          case 90: break;
          case 35: 
            { return symbol(sym.and_op);
            }
          case 91: break;
          case 36: 
            { return symbol(sym.mod_op);
            }
          case 92: break;
          case 37: 
            { return symbol(sym.end);
            }
          case 93: break;
          case 38: 
            { return symbol(sym.not_op);
            }
          case 94: break;
          case 39: 
            { return symbol(sym.div_op);
            }
          case 95: break;
          case 40: 
            { return symbol(sym.var);
            }
          case 96: break;
          case 41: 
            { return symbol(sym.for_t);
            }
          case 97: break;
          case 42: 
            { return symbol(sym.else_t);
            }
          case 98: break;
          case 43: 
            { return symbol(sym.case_t);
            }
          case 99: break;
          case 44: 
            { return symbol(sym.then_t);
            }
          case 100: break;
          case 45: 
            { return symbol(sym.type);
            }
          case 101: break;
          case 46: 
            { return symbol(sym.real_name);
            }
          case 102: break;
          case 47: 
            { return symbol(sym.array);
            }
          case 103: break;
          case 48: 
            { return symbol(sym.begin);
            }
          case 104: break;
          case 49: 
            { return symbol(sym.const_t);
            }
          case 105: break;
          case 50: 
            { return symbol(sym.while_t);
            }
          case 106: break;
          case 51: 
            { return symbol(sym.record);
            }
          case 107: break;
          case 52: 
            { return symbol(sym.program);
            }
          case 108: break;
          case 53: 
            { return symbol(sym.int_name);
            }
          case 109: break;
          case 54: 
            { return symbol(sym.function);
            }
          case 110: break;
          case 55: 
            { return symbol(sym.procedure);
            }
          case 111: break;
          case 56: 
            { return symbol(sym.char_name);
            }
          case 112: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
